#!/bin/sh
#
# Load wifi kernel modules
#

case "$1" in
  start)
	printf "Loading brcmfmac"
	/sbin/modprobe brcmfmac
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

